name: Generate and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate plots
        run: python typing_metrics.py

      - name: Upload PNG files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plots
          path: |
            daily_averages.png
            scatter.png
            histogram.png


